### ISSUE TITLE
Hyperclick doesn't work with python-language-server 0.21.3

### ISSUE THREAD

**Issue by novns** [lgeiger/ide-python#143]
Hyperclick is broken after the last update of python-language-server.

There are errors in `nohup.out` like this one:

```
[2018-11-24 15:39:15.472] [ERROR] atom-ide-definitions - Error getting definition for /home/novns/Projects/Freelance/videobot/videobot.py { Error: TypeError: goto_assignments() got an unexpected keyword argument 'enabled'
    at handleResponse (/home/novns/Projects/.atoms/videobot/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/home/novns/Projects/.atoms/videobot/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.setImmediate (/home/novns/Projects/.atoms/videobot/packages/ide-python/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
  code: -32602,
  data: 
   { traceback: 
      [ '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/jsonrpc/endpoint.py", line 113, in consume\n    self._handle_request(message[\'id\'], message[\'method\'], message.get(\'params\'))\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/jsonrpc/endpoint.py", line 182, in _handle_request\n    handler_result = handler(params)\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/jsonrpc/dispatchers.py", line 23, in handler\n    return method(**(params or {}))\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pyls/python_ls.py", line 261, in m_text_document__definition\n    return self.definitions(textDocument[\'uri\'], position)\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pyls/python_ls.py", line 193, in definitions\n    return flatten(self._hook(\'pyls_definitions\', doc_uri, position=position))\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pyls/python_ls.py", line 118, in _hook\n    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pluggy/_tracing.py", line 80, in __call__\n    return outcome.get_result()\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pluggy/callers.py", line 52, in from_call\n    result = func()\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pluggy/_tracing.py", line 78, in <lambda>\n    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>\n    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall\n    return outcome.get_result()\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall\n    res = hook_impl.function(*args)\n',
        '  File "/home/novns/Projects/Freelance/videobot/venv/lib/python3.7/site-packages/pyls/plugins/definition.py", line 11, in pyls_definitions\n    definitions = document.jedi_script(position).goto_assignments(**params)\n' ] },
  rawStack: 
   [ CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {} ] }
```

Downgrading to python-language-server 0.21.2 resolves the problem.

**Comment by lgeiger** [comment]
This was fixed in version 0.21.4: https://github.com/palantir/python-language-server/pull/457

Upgrading to `ide-python@1.1.0` will additionally add support for following imports
